### ISSUE TITLE
Where is the TokenArtifact.json and contract-address.json from dapp.js ?

### ISSUE THREAD

**Issue by crapthings** [nomiclabs/hardhat-hackathon-boilerplate#33]
import TokenArtifact from "../contracts/Token.json";
import contractAddress from "../contracts/contract-address.json";

Should I compile contracts into the src folder?

**Comment by crapthings** [comment]
problem solved

**Comment by castorinop** [comment]
Same problem.
> problem solved
Solved how ?

**Comment by crapthings** [comment]
@castorinop 

https://github.com/crapthings/hardhat-dapp-starter
https://github.com/crapthings/hardhat-dapp-starter#connect-to-your-contract-address

https://github.com/crapthings/hardhat-dapp-starter/blob/main/dapp-ui/src/stores/index.js#L8
