### ISSUE TITLE
Double hardhatToken.deployed() calls in test set up

### ISSUE THREAD

**Issue by ahmadizzan** [nomiclabs/hardhat-hackathon-boilerplate#34]
Hi,

I am new to the hardhat ecosystem and trying to learn more about it! when reading `test/Token.js`, I noticed that the test called `hardhatToken.deployed()` twice. Here are the relevant code.

```javascript
// `beforeEach` will run before each test, re-deploying the contract every
// time. It receives a callback, which can be async.
beforeEach(async function () {
  // Get the ContractFactory and Signers here.
  Token = await ethers.getContractFactory("Token");
  [owner, addr1, addr2, ...addrs] = await ethers.getSigners();

  // To deploy our contract, we just have to call Token.deploy() and await
  // for it to be deployed(), which happens onces its transaction has been
  // mined.
  hardhatToken = await Token.deploy();
  await hardhatToken.deployed();

  // We can interact with the contract by calling `hardhatToken.method()`
  await hardhatToken.deployed();
});
```

Want to confirm the purpose of the second call `hardhatToken.deployed()`? my initial assumption is that it is just to demonstrate how to access method in the contract, but just want to make sure that it is the intended purpose. Thanks!

**Comment by alcuadrado** [comment]
@ahmadizzan that's actually a mistake. Do you wanna send a PR removing the first occurrence?

**Comment by ahmadizzan** [comment]
Yes! will update you with the PR for the fix, thanks!

**Comment by ahmadizzan** [comment]
Hi @alcuadrado , I have created the PR to fix the issue. Let me know what you think, thanks!

PR: https://github.com/nomiclabs/hardhat-hackathon-boilerplate/pull/35

**Comment by alcuadrado** [comment]
thanks!
