### ISSUE TITLE
Ganache dependency error

### ISSUE THREAD

**Issue by jeffprestes** [nomiclabs/hardhat-hackathon-boilerplate#4]
After clone the repo and try to run ```npm install``` I am getting this error:

```bash
src/github.com/nomiclabs/hardhat-hackathon-boilerplate (master)$ npm i
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/ganache-core/node_modules/web3-provider-engine/node_modules/eth-sig-util/ethereumjs-abi@git+https:/github.com/ethereumjs/ethereumjs-abi.git" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeffprestes/.npm/_logs/2020-10-23T17_30_42_568Z-debug.log
```

I have another hardhat (buildler) project and it is working. I was justing testing this repo for teaching purposes and got this error.

**Comment by alcuadrado** [comment]
Hi @jeffprestes,

This problem is being tracked here: https://github.com/trufflesuite/ganache-core/issues/650#issuecomment-714393379

Apparently `npm ci` works.

**Comment by jeffprestes** [comment]
Thanks @alcuadrado for the quick answer.
If you allow me give a suggestion, maybe update README.md with this note might help another users. 
What do you think?

**Comment by alcuadrado** [comment]
Great idea! Thanks!
